// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core"

export {}

declare module "@vue/runtime-core" {
    export interface GlobalComponents {
        Button: typeof import("./src/components/base/button.vue")["default"]
        IconClose: typeof import("./src/components/base/icon/icon-close.vue")["default"]
        IconDrag: typeof import("./src/components/base/icon/icon-drag.vue")["default"]
        IconMinus: typeof import("./src/components/base/icon/icon-minus.vue")["default"]
        IconPlus: typeof import("./src/components/base/icon/icon-plus.vue")["default"]
        RouterLink: typeof import("vue-router")["RouterLink"]
        RouterView: typeof import("vue-router")["RouterView"]
    }
}
